GET http://localhost:3003/users
###

POST http://localhost:3003/users
Content-Type: application/json

  {
    "id": "u004",
    "name": "Amandinha",
    "email": "amandinha@email.com",
    "password": "44239212",
    "role": "user"
  }
###

PUT http://localhost:3003/users/u009
Content-Type: application/json

  {
    "id": "u006",
    "name": "Joãozinho",
    "email": "joazinho@email.com",
    "password": "88239111",
    "role": "admin"
  }
###

delete http://localhost:3003/users/u004
###